Sample App - Avoid showing consent screen twice for same pending/push challenge
okta/okta-devices-swift pull request #54
Opened 2022-08-26 16:23 UTC by moisesolmedo-okta

Checking by transactionID before presenting the user consent screen

2022-08-26 18:21 UTC, IldarAbdullin-okta requested changes
It is not recommended to start `resolve` flow and abandon it. It is better to drop challenge early after `parsing` step

2022-08-26 18:21 UTC, IldarAbdullin-okta commented on Examples/PushSampleApp/SampleApp/RootCoordinator.swift
> +        if !isPresentingSameChallenge(nav: nav, newStep: remediationStep) {
Why even ask sdk to resolve challenge if we can drop early after `parseChallenge` step?

2022-08-26 21:08 UTC, moisesolmedo-okta commented on Examples/PushSampleApp/SampleApp/RootCoordinator.swift
> +        if !isPresentingSameChallenge(nav: nav, newStep: remediationStep) {
good point. Changed it to drop after parsing the challenge.

2022-08-26 21:57 UTC, IldarAbdullin-okta commented on Examples/PushSampleApp/SampleApp/PushNotificationService.swift
> +        guard !(delegate?.isPresentingSameChallenge(newStep: pushChallenge) ?? false) else { return }
Still looks complicated. Why just not create queue/array that keeps unhandled/in-progress challenges? In that case you can use array to find whether challenge is unique or duplicate

2022-08-26 21:58 UTC, IldarAbdullin-okta commented on Examples/PushSampleApp/SampleApp/PushNotificationService.swift
> +        guard !(delegate?.isPresentingSameChallenge(newStep: pushChallenge) ?? false) else { return }
You can kick-out challenges in `onCompletion` closure below

2022-08-29 19:53 UTC, IldarAbdullin-okta approved these changes
Nice! 👍

2022-08-29 19:53 UTC, IldarAbdullin-okta commented on Examples/PushSampleApp/SampleApp/PushNotificationService.swift
> +            self.unhandledChallenges.remove(pushChallenge.transactionId)
Just want to make sure that we inserting and removing on UI thread, correct?

2022-08-29 19:53 UTC, IldarAbdullin-okta commented on Examples/PushSampleApp/SampleApp/PushNotificationService.swift
> +                    self.logger?.info(eventName: LoggerEvent.account.rawValue, message: "Success resolving push challenge")
👍

2022-08-29 20:13 UTC, moisesolmedo-okta commented on Examples/PushSampleApp/SampleApp/PushNotificationService.swift
> +            self.unhandledChallenges.remove(pushChallenge.transactionId)
Turns out the completion was being dispatched to a different NSURLSession queue. Moved the removal to UI thread.

2022-08-29 21:24 UTC, merged