Add CIBA option on EnrollmentParams and add Capabilities object on enrollment request
okta/okta-devices-swift pull request #59
Opened 2022-09-26 20:41 UTC by moisesolmedo-okta

### Problem Analysis (Technical)
Enrollment payload adds a new `capabilities` field
```
"methods": [
    {
      "type": "push",
      "apsEnvironment": "development",
      "pushToken": "667b773e90871f014805f45f770c90d161b84b609d167039b2c388c7bacfdaa1",
      "capabilities": {
          "transactionTypes" : [
            "LOGIN",
            "CIBA"
          ]
      }
      "keys": {
        ....
      }
    }
  ]
}
```

### Solution (Technical)
Added a new method on `EnrollmentParams` called
`func enableCIBATransactions(enable: Bool) { }` that adds a new property on `EnrollmentContext` and will append a new `Capabilities` object to the enrollment request.

### Affected Components

### Steps to reproduce:

Actual result:

Expected result:

### Tests

2022-10-06 21:27 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Transactions/TransactionType.swift
> +public enum TransactionType: String, Encodable {
Great suggestion about bitmask, made things much simpler. Updated

2022-10-06 21:28 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Enrollment/EnrollmentParameters.swift
> +    var isCIBAEnabled: Bool = true
Yes changed it to .login only by default.

2022-10-10 22:20 UTC, IldarAbdullin-okta requested changes
Overall looks good. Please address comments

2022-10-10 22:26 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Transactions/TransactionType.swift
> +    public static func initEnrollmentTypes(supportsCiba: Bool) -> Self {
these are the default values an enrollment should support if ciba is enabled (both .login and .ciba) but this method is only used when creating the enrollmentContext so I guess I can remove this from here and move it there.

2022-10-11 02:09 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var bindingMessage: String? { get }
Not sure if that's the best solution. All of the existing interfaces return a `PushChallengeProtocol` type. How would they know if the returned push challenge supports CIBA? the only way is by leaving `transactionType` on `PushChallengeProtocol` and creating `CIBAChallengeProtocol` with only `bindingMessage` as a property. Is that what you have in mind? seems good for separation but not very obvious to me for devs.

They will have to do something like:
```swift
if pushChallenge.transactionType == .ciba {
    let cibaChallenge = (pushChallenge as? CIBAChallengeProtocol)
    label.text = cibaChallenge?.bindingMessage
}
```

Doesn't seem very obvious to me, is that what you have in mind?

2022-10-11 02:17 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var bindingMessage: String? { get }
Another option I can think of is extending `PushChallengeProtocol` like this
```
public extension PushChallengeProtocol {
    var cibaPushChallenge: CIBAChallengeProtocol? {
        guard transactionType == .ciba else { return nil }
        return self as? CIBAChallengeProtocol
    }
}
```
That way we can have `PushChallengeProtocol` and `CIBAChallengeProtocol` separated somehow but still available for devs to use them.

2022-10-11 15:47 UTC, IldarAbdullin-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var transactionType: TransactionType { get }
BTW, this is extra if there will be `CIBAChallengeProtocol`

2022-10-11 19:08 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var bindingMessage: String? { get }
I think it makes sense. What I ended up doing was creating a new `CIBAChallengeProtocol` that extends `PushChallengeProtocol` as you suggested. But I left `transactionType` on the `PushChallenge` concrete type because we need a way to know what type to pass to the `RemediationStepUserConsent` object. 
This way when devs downcast `ChallengeProtocol` to `CIBAPushChallenge` it will return nil if the challenge is not ciba. Thoughts?

2022-10-11 19:11 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Transactions/OktaTransactionPushChallenge.swift
> +            let abstractPushChallenge = pushChallenge.transactionType == .ciba ? pushChallenge as CIBAChallengeProtocol : pushChallenge as PushChallengeProtocol
The way I see it this is how we pass the correct type downstream to the UserConsent object. We need a way to check the `transactionType` so devs can cast it accordingly.

2022-10-11 19:12 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Transactions/OktaTransactionPushChallenge.swift
> +            let abstractPushChallenge = pushChallenge.transactionType == .ciba ? pushChallenge as CIBAChallengeProtocol : pushChallenge as PushChallengeProtocol
The way I see it this is how we pass the correct type downstream to the UserConsent object. We need a way to check the `transactionType` so devs can cast it accordingly.

2022-10-11 19:17 UTC, IldarAbdullin-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var bindingMessage: String? { get }
Devs can use `challenge is CIBAPushChallenge ` to easily check whether challenge is indeed CIBA or not. That is the main reason why I think that transactionType is superfluous property

2022-10-11 19:22 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var bindingMessage: String? { get }
Yes devs won't get access to 'transactionType'. It's only accessible on the concrete type for us but not on the protocol that we make public. They can cast accordingly to CIBAChallengeProtocol as you're suggesting.

2022-10-11 19:33 UTC, IldarAbdullin-okta commented on Sources/DeviceAuthenticator/PushChallengeProtocol.swift
> +    var bindingMessage: String? { get }
Ok, got it

2022-10-18 16:06 UTC, moisesolmedo-okta commented
@IldarAbdullin-okta Merge conflicts solved, ready for 👁️

2022-10-20 00:17 UTC, moisesolmedo-okta commented
@IldarAbdullin-okta Merge conflicts solved again 👁️

2022-10-21 16:24 UTC, IldarAbdullin-okta approved these changes
LGTM!

2022-10-21 16:24 UTC, IldarAbdullin-okta commented on Tests/DeviceAuthenticatorUnitTests/PushChallengeTests.swift
> +class PushChallengeTests: XCTestCase {
I think we already have test suite for PushChallenge, no?

2022-10-21 16:39 UTC, moisesolmedo-okta commented on Tests/DeviceAuthenticatorUnitTests/PushChallengeTests.swift
> +class PushChallengeTests: XCTestCase {
Searched and we have `FactorChallengeTests` for PushChallenge tests :). Not sure why it's named like this. Will rename.

2022-10-21 16:59 UTC, merged