Implement MyAccount download policy server API
okta/okta-devices-swift pull request #67
Opened 2022-10-18 22:20 UTC by IldarAbdullin-okta

### Problem Analysis (Technical)
Not implemented

### Solution (Technical)
Prepare models and implement API for downloading policy

### Affected Components

### Steps to reproduce:

Actual result:

Expected result:

### Tests
Added

2022-10-18 22:28 UTC, FeiChen-okta approved these changes

2022-10-19 18:01 UTC, moisesolmedo-okta approved these changes

2022-10-19 18:02 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Networking/MethodSettingsModel.swift
> +    enum TransactionType: String, Codable {
did you add this? I named this model `TransactionTypesModel` to not conflict with the bitmask

2022-10-19 18:06 UTC, moisesolmedo-okta requested changes
Please see my comment about `TransactionType`

2022-10-19 18:30 UTC, IldarAbdullin-okta commented on Sources/DeviceAuthenticator/Networking/MethodSettingsModel.swift
> +    enum TransactionType: String, Codable {
Its full name is MethodSettingsModel. TransactionType, it is scoped by MethodSettingsModel namespace
I don't see any problem

2022-10-19 18:32 UTC, moisesolmedo-okta commented on Sources/DeviceAuthenticator/Networking/MethodSettingsModel.swift
> +    enum TransactionType: String, Codable {
should be fine then.

2022-10-19 18:33 UTC, merged